"""empty message

Revision ID: 88d545f64b94
Revises: 3e749571ea87
Create Date: 2025-08-07 15:56:19.425920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d545f64b94'
down_revision = '3e749571ea87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('live_link', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('github_link', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('github_link')
        batch_op.drop_column('live_link')

    # ### end Alembic commands ###
